# 選擇帶有 Node.js 的基礎映像
FROM node:16

# 設定工作目錄
WORKDIR /app

# 複製 package.json 和 package-lock.json（如果存在）
COPY package*.json ./

# 安裝項目依賴
RUN npm install

# 複製項目文件到容器中
COPY . .

# 指定運行時的端口
EXPOSE 3001

# 使用 npm run start 啟動應用
CMD ["npm", "run", "start"]
