# 使用 node 的官方镜像作为基础镜像
FROM node:latest

# 设置容器内的工作目录
WORKDIR /app

# 复制 package.json 和 package-lock.json（如果存在）文件到工作目录
COPY package*.json ./

# 安装项目依赖
RUN npm install

# 复制剩余的前端源代码到工作目录
COPY . .

# 构建应用
RUN npm run build

# 安装一个简单的 HTTP 服务器来服务静态文件
RUN npm install -g serve

# 设置容器对外暴露的端口号
EXPOSE 3001

# 运行 HTTP 服务器
CMD ["serve", "-s", "build", "-l", "3001"]
